Atividades_FLASK/Atividade_MVC/models/__init__.py
__all__ = [
    'user',
    'book',
    'loan'
]

Atividades_FLASK/Atividade_MVC/models/book.py
from database import get_connection

class Book:
    def __init__(self, titulo, user_id):
        self.titulo = titulo
        self.user_id = user_id

    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO books(titulo, user_id) values(?,?)", (self.titulo, self.user_id))
        conn.commit()
        conn.close()
        return True

    @classmethod
    def all(cls):
        conn = get_connection()
        books = conn.execute("SELECT * FROM books").fetchall()
        return books

Atividades_FLASK/Atividade_MVC/models/loan.py
from database import get_connection

class Loan:
    def __init__(self, book_id, user_id):
        self.book_id = book_id
        self.user_id = user_id

    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO loans(book_id, user_id) values(?,?)", (self.book_id, self.user_id))
        conn.commit()
        conn.close()
        return True

    @classmethod
    def all(cls):
        conn = get_connection()
        loan = conn.execute('''
            SELECT loans.*, users.nome AS user_name, books.titulo AS book_title 
            FROM loans
            JOIN users ON loans.user_id = users.id
            JOIN books ON loans.book_id = books.id
        ''').fetchall()
        return loan

Atividades_FLASK/Atividade_MVC/models/user.py
from database import get_connection

class User:
    def __init__(self, email, nome):
        self.nome = nome
        self.email = email
        
    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO users(email, nome) values(?,?)", (self.email, self.nome))
        conn.commit()
        conn.close()
        return True
    
    @classmethod
    def all(cls):
        conn = get_connection()
        users = conn.execute("SELECT * FROM users").fetchall()
        return users

Atividades_FLASK/Atividade_MVC/app.py
from flask import Flask
from controllers import users, books, loans

app = Flask(__name__)
app.register_blueprint(users.bp)
app.register_blueprint(books.bp)
app.register_blueprint(loans.bp)

Atividades_FLASK/Atividade_MVC/controllers/__init__.py
__all__ = [
    'books',
    'users',
    'loans'
]

Atividades_FLASK/Atividade_MVC/controllers/books.py
from flask import Flask, render_template, url_for, request, Blueprint, redirect
from models.user import User
from models.book import Book

bp = Blueprint('books', __name__, url_prefix='/books')

@bp.route('/')
def index():
    return render_template('books/index.html', books = Book.all())

@bp.route('/register', methods=['POST', 'GET'])
def register():
    
    if request.method == 'POST':
        titulo = request.form['titulo']
        user = request.form['user']

        book = Book(titulo, user)
        book.save()
        return redirect(url_for('books.index'))


    return render_template('books/register.html', users=User.all())

Atividades_FLASK/Atividade_MVC/controllers/loans.py
from flask import render_template, Blueprint, url_for, request, flash, redirect
from models.loan import Loan
from models.book import Book
from models.user import User

bp = Blueprint('loans', __name__, url_prefix='/loans')

@bp.route('/')
def index():
    return render_template('loans/index.html', loans = Loan.all())

@bp.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        user_id = request.form['user']
        book_id = request.form['book']

        loan = Loan(book_id, user_id)
        loan.save()
        return redirect(url_for('loans.index'))
    
    return render_template('loans/register.html', users=User.all(), books=Book.all())

Atividades_FLASK/Atividade_MVC/controllers/users.py
from flask import render_template, Blueprint, url_for, request, flash, redirect
from models.user import User

bp = Blueprint('users', __name__, url_prefix='/users')

@bp.route('/')
def index():
    return render_template('users/index.html', users = User.all())

@bp.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        email = request.form['email']
        nome= request.form['nome']

        if not email:
            flash('Email é obrigatório')
        else:
            user = User(email, nome)
            user.save()
            return redirect(url_for('users.index'))
    
    return render_template('users/register.html')

Atividades_FLASK/Atividade_MVC/templates/loans/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>Lista de Empréstimos</h1>

    <a href="{{url_for('loans.register')}}">Adicionar empréstimo</a>
    <hr>
    {% for loan in loans %}
    <div style="background-color: beige; margin: 15px 0;">
        <p>Nome: {{loan.user_name}}</p>
        <p>Titulo do Livro: {{loan.book_title}}</p>
        <p>Data de empréstimo: {{loan.data_emprestimo}}</p>
        <p>Data de devolução: {{loan.data_devolucao}}</p>
    </div>
    {% endfor %}
    
    
    
</body>
</html>

Atividades_FLASK/Atividade_MVC/templates/loans/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Empréstimo - Register</title>
</head>
<body>

    <h1>Registrar Empréstimos</h1>

    <div>
        <h2>Dados</h2>
        <form action="{{url_for('loans.register')}}" method="post">
            <select name="user">
                {% for user in users %}
                    <option value="{{user.id}}">{{user.nome}}</option>    
                {% endfor %}                
            </select>

            <select name="book">
                {% for book in books %}
                    <option value="{{book.id}}">{{book.titulo}}</option>    
                {% endfor %}                
            </select>
            <button>Enviar</button>
        </form>
    </div>
    
</body>
</html>

Atividades_FLASK/Atividade_MVC/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>Lista de Usuários</h1>

    <a href="{{url_for('users.register')}}">Adicionar</a>

    <hr>
    {% for user in users %}
    <p>{{user.nome}}</p>
    {% endfor %}
    
</body>
</html>

Atividades_FLASK/Atividade_MVC/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Registro de Usuários</h1>
    <div>
        <h2>Dados</h2>
        <form action="{{url_for('users.register')}}" method="post">
            <input type="email" name="email" placeholder="Email" value="{{request.form['email']}}">
            {% with error = get_flashed_messages()  %}
            <span class="warning">{{error[0]}}</span>    
            {% endwith %}    
            <input type="text" name="nome" placeholder="Nome" value="{{request.form['nome']}}">
            <button>Enviar</button>
        </form>
    
    </div>

</body>
</html>